version: '3'
services:
  composedocker:
    image: summerschool:latest
    container_name: ROBOTOLOGY  # Specifica il nome del container
    ports:
      - "10000:10000/tcp"
      - "10000:10000/udp"
    devices:
      #add camera
      - "/dev/video1:/dev/video1"
      #add microphone
      - "/dev/snd:/dev/snd"
      #- "/dev/ttyUSB0:/dev/ttyUSB0" #comment out this if you don't have plugged the iCube serial RX device 
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /home/icub/.gazebo/models:/usr/local/share/gazebo/models
      - /home/icub/Documents/hriworkshopthriss/modules/gazebo:/usr/local/share/gazebo/worlds
    environment:
      - DISPLAY=$DISPLAY
    stdin_open: true
    tty: true
    restart: always