version: "3.8"
services:
  object_recognition:
    container_name: face-detector
    image: ${DOCKER_REGISTRY_IP}:5000/img-object-detector
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    network_mode: "host"
    secrets:
      - source: ssh_key
        target: /root/.ssh/id_rsa
    environment:
      - DOCKER_REGISTRY_IP=${DOCKER_REGISTRY_IP}
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - YARP_NAMESPACE=@YARP_NAMESPACE@
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - /dev/bus/usb:/dev/bus/usb
      - /dev/snd:/dev/snd
    privileged: true
    entrypoint: /entrypoint.sh
    command: /run_face_detector.sh 1280 720
secrets:
  known_hosts:
    file: ~/.ssh/known_hosts
  ssh_key:
    file: ~/.ssh/id_rsa